# Generated by Django 4.0.5 on 2023-06-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Full_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offers', models.CharField(max_length=255)),
                ('cuisines', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('price_range', models.IntegerField()),
                ('mezzo_provider', models.CharField(max_length=255)),
                ('order_deeplink', models.CharField(max_length=255)),
                ('has_table_booking', models.BooleanField()),
                ('is_delivering_now', models.BooleanField()),
                ('opentable_support', models.BooleanField()),
                ('has_online_delivery', models.BooleanField()),
                ('include_bogo_offers', models.CharField(max_length=10)),
                ('average_cost_for_two', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_book_form_web_view', models.BooleanField()),
                ('book_form_web_view_url', models.CharField(max_length=255)),
                ('is_table_reservation_supported', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=520)),
                ('city_id', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('locality', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('country_id', models.IntegerField()),
                ('locality_verbose', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField()),
                ('rating_text', models.CharField(max_length=255)),
                ('rating_color', models.CharField(max_length=255)),
                ('aggregate_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('lat_long', models.CharField(max_length=255)),
                ('full_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchbar.full_details')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchbar.item')),
            ],
        ),
        migrations.AddField(
            model_name='full_details',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchbar.location'),
        ),
        migrations.AddField(
            model_name='full_details',
            name='user_rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchbar.user_rating'),
        ),
    ]
