# Generated by Django 4.0.5 on 2023-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='items',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='items',
            field=models.ManyToManyField(to='searchbar.item'),
        ),
    ]
